version: '3'
 
services:
  web:
    command: python3 main.py
    image: group6/ait-ml-group-project:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - 8080:80
  
  mlflow:
    image: akraradets/ait-ml-mlflow:2023
    platform: linux/x86_64
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    volumes:
      - ./_mlflow:/mlflow
    ports:
      - 5000:5000